### ISSUE TITLE
Should config's tag property be optional?

### ISSUE THREAD

**Issue by szymnwk** [knaadh/nestjs-drizzle#10]
I was trying to set up the DrizzlePostgresModule with just one Drizzle instance. I was planning to have just that one instance (at least for now), so I figured I wouldn't tag it as the documentation says _"You **can** inject the Drizzle instances using their respective tag specified in the configuration"_. I wasn't able to get the DI of the service working. Once I specified the tag, it worked. Is it me misunderstanding something here, or is the documentation and the config type specification misleading, and the tag shouldn't, in fact, be optional?

**Comment by mithleshjs** [comment]
It is optional indeed. Can you share how you were injecting the instance?

**Comment by szymnwk** [comment]
To begin with, like below, which yielded the following error:

<img width="549" alt="image" src="https://github.com/user-attachments/assets/e193f8d0-2560-44fb-a35e-f4c40f6f0739">
<img width="581" alt="image" src="https://github.com/user-attachments/assets/2446a6f3-3f69-4298-9459-10ee2ae8a083">

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/a7197d24-1110-4638-aa4c-2e23e001fdc2">

It then worked when I did this:

<img width="537" alt="image" src="https://github.com/user-attachments/assets/7e7468c5-8e4a-4a6a-9574-ea3ee5ae285c">

<img width="602" alt="image" src="https://github.com/user-attachments/assets/a02a48cd-bac6-4e78-b505-8fb53783fd48">

**Comment by mithleshjs** [comment]
The error occurred because `@Inject()` needs a token which you have not specified. The `tag` is used as a token to inject the drizzle instance. If you don't specify a tag in the config, its default value is used which is `default`.  So inject it this way `@Inject('default')`

**Comment by szymnwk** [comment]
It works now. Thanks a lot!
