### ISSUE TITLE
Expose Configs

### ISSUE THREAD

**Issue by ben-hn** [knaadh/nestjs-drizzle#12]
Currently when trying to use a config service, I need to 

`import { DrizzlePostgresConfig } from '@knaadh/nestjs-drizzle-postgres/src/postgres-js.interface';`

Could you export it higher up? Thanks!

**Comment by mithleshjs** [comment]
Thanks for bringing it to the notice that types are not exported the way they should. I will fix get it fixed in a day or two.

**Comment by mithleshjs** [comment]
> Currently when trying to use a config service, I need to
> 
> `import { DrizzlePostgresConfig } from '@knaadh/nestjs-drizzle-postgres/src/postgres-js.interface';`
> 
> Could you export it higher up? Thanks!
Try this way - import DrizzlePostgresConfig from "@knaadh/nestjs-drizzle-postgres";

**Comment by mithleshjs** [comment]
> Currently when trying to use a config service, I need to
> 
> `import { DrizzlePostgresConfig } from '@knaadh/nestjs-drizzle-postgres/src/postgres-js.interface';`
> 
> Could you export it higher up? Thanks!

Try this way - `import DrizzlePostgresConfig from "@knaadh/nestjs-drizzle-postgres";`

**Comment by ben-hn** [comment]
TS2709: Cannot use namespace DrizzlePostgresConfig as a type.
________________________________

**Comment by mithleshjs** [comment]
It worked fine on Bun, so it may not be working with other package managers or Node. So I will export the types in the update.

**Comment by mithleshjs** [comment]
#14
