### ISSUE TITLE
Unable to inject untagged drizzle

### ISSUE THREAD

**Issue by ben-hn** [knaadh/nestjs-drizzle#13]
Not sure if this one is you or nest, but if you don't specify a tag in the `registerAsync` method, it defaults to `default`, however I can't seem to get it back using just '@Inject()`, only with `@Inject('default')`.

Maybe an `@InjectDrizzle` decorator would do this?

**Comment by mithleshjs** [comment]
Inject can't work without the token according to Nest standard. @InjectDrizzle() could be created as a alternative decorator 👍

**Comment by mithleshjs** [comment]
#15
