### ISSUE TITLE
Jest: testing example

### ISSUE THREAD

**Issue by johaven** [knaadh/nestjs-drizzle#2]
Hi,

could you provide an example to import correctly the service in a jest context (spec.ts)

I imported the module (with the right configuration) but i can inject the service like this.

I got this error:
```bash
Nest can't resolve dependencies of the CONFIGURABLE_MODULE_OPTIONS[893894bbe338ad95073e5] (?). Please make sure that the argument ConfigService at index [0] is available in the DrizzleMySqlModule context.

Potential solutions: Is DrizzleMySqlModule a valid NestJS module?
```

i import the module like this:

```ts
DrizzleMySqlModule.registerAsync({
      tag: DB_TAG,
      inject: [ConfigService],
      useFactory: async (cs: ConfigService): Promise<DrizzleMySqlConfig> => ({
        mysql: {
          connection: 'pool',
          config: cs.get<any>('mysql.config')
        },
        config: {
          schema: { ...schema },
          mode: 'default',
          logger: cs.get<boolean>('mysql.logQueries') ? new DatabaseLogger() : false
        }
      })
    })
```

**Comment by mithleshjs** [comment]
Are getting error in just test or in normal use also?

**Comment by johaven** [comment]
Only in jest

**Comment by johaven** [comment]
Ok, i got it.
The Nest ConfigModule must be imported (with global option) in the jest test to give access to the ConfigService in the DrizzleMySql Module.
Then to use the database from the test services, you must inject it in this way.

```ts
providers: [{ provide: 'db', useValue: TAG_GIVEN_TO_MODULE }, ...]
```

A short documentation on this might be helpful :)
