### ISSUE TITLE
[BUG] types not passed to result

### ISSUE THREAD

**Issue by frct1** [knaadh/nestjs-drizzle#4]
Hello,
Is it known bug that result's types are not being inherited ?
Just wrapped everything up with basic users schema 🤷‍♂️  though `.query.users` works
<img width="620" alt="image" src="https://github.com/knaadh/nestjs-drizzle/assets/25178244/33209512-5734-4613-ba63-8ae444895dd5">

**Comment by mithleshjs** [comment]
Yes, it happens when `strictNullChecks` is set to `false` in the `tsconfig` file. This has been reported here: https://github.com/drizzle-team/drizzle-orm/issues/1730
