### ISSUE TITLE
Dependency injection and multiple DB types

### ISSUE THREAD

**Issue by vitorpy** [knaadh/nestjs-drizzle#7]
Db types and schemas don't share parent classes in Drizzle (it's a thin layer, after all). However, I _really_ wanted to inject a Sqlite database to use during local testing, while using MySQL in production. I tried to use some union types:

![image](https://github.com/knaadh/nestjs-drizzle/assets/12871/55627dd5-c20e-4eb7-8ea9-58cf5155cca5)

but `eslint` doesn't like this solution. I was wondering if you have done something similar and have some words of advice?

**Comment by mithleshjs** [comment]
I didn't fully understand the whole implementation from the above code snippet. Please provide more information or full code so I look into it. However, I can suggest you an alternative approach which involves conditionally loading modules based on `env` values as explained [here](https://docs.nestjs.com/techniques/configuration#conditional-module-configuration) 

Here an example: 

```typescript
import { DrizzleBetterSQLiteModule } from '@knaadh/nestjs-drizzle-better-sqlite3';
import { DrizzleMySqlModule } from '@knaadh/nestjs-drizzle-mysql2';
import { Module } from '@nestjs/common';
import { ConditionalModule, ConfigModule } from '@nestjs/config';

import { AppController } from './app.controller';
import { AppService } from './app.service';
import * as mySQLSchema from './schema';
import * as sqliteSchema from './schema2';

@Module({
  imports: [
    ConfigModule.forRoot(),
    ConditionalModule.registerWhen(
      DrizzleMySqlModule.register({
        tag: 'DB',
        mysql: {
          connection: 'client',
          config: {
            host: '127.0.0.1',
            user: 'root',
            database: 'drizzleDB',
          },
        },
        config: { schema: { ...mySQLSchema }, mode: 'default' },
      }),
      (env: NodeJS.ProcessEnv) => env['APP_ENV'] == 'PRODUCTION',
    ),
    ConditionalModule.registerWhen(
      DrizzleBetterSQLiteModule.register({
        tag: 'DB',
        sqlite3: {
          filename: 'demo.db',
        },
        config: { schema: { ...sqliteSchema } },
      }),
      (env: NodeJS.ProcessEnv) => env['APP_ENV'] == 'TESTING',
    ),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
