### ISSUE TITLE
Missing `OnApplicationShutdown` implementation?

### ISSUE THREAD

**Issue by cayter** [knaadh/nestjs-drizzle#8]
NestJS TypeORM does implement [onApplicationShutdown()](https://github.com/nestjs/typeorm/blob/master/lib/typeorm-core.module.ts#L141C9-L141C30) to close the DB connections right before the server is shut down. It seems that this isn't implemented in the library yet, is that correct?

In addition, is there a reason why we don't have `forRoot()` and `forRootAsync()` since we'd only need to initialise the DB once?

**Comment by mithleshjs** [comment]
> NestJS TypeORM does implement [onApplicationShutdown()](https://github.com/nestjs/typeorm/blob/master/lib/typeorm-core.module.ts#L141C9-L141C30) to close the DB connections right before the server is shut down. It seems that this isn't implemented in the library yet, is that correct?

Yes, you are right and thanks for bringing it to the notice. Since Drizzle doesn't provide an API to close connections, we will have to do it using the underlying driver API. I will add another optional parameter to auto close connections on shutdown.

**Comment by mithleshjs** [comment]
> In addition, is there a reason why we don't have `forRoot()` and `forRootAsync()` since we'd only need to initialise the DB once?

We use `register` and `registerAsync` instead of `forRoot()` and `forRootAsync()` accoring to our internal coding convention and also they are the default methods if you use [configurable module builder](https://docs.nestjs.com/fundamentals/dynamic-modules#configurable-module-builder)

**Comment by mithleshjs** [comment]
@cayter I looked into it and saw no need to implement this as connection do get closed after the app goes down. Also, I don't know how connections are managed internally by Drizzle. But if there are issues with hanging connections or such do let me know.

**Comment by cayter** [comment]
Drizzle ORM type doesn't define it, we'd have to define it ourselves but we can already access it like this:

```
import { type PostgresJsDatabase, drizzle } from "drizzle-orm/postgres-js";

export type DB<T extends Record<string, unknown>> =
	PostgresJsDatabase<T> & {
		session: {
			client: postgres.Sql<T>;
		};
	};
	
const orm = drizzle(client, { schema }) as DB<typeof schema>;
await orm.session.client.end(); // this is how postgres.js close the connections
```

**Comment by cayter** [comment]
> saw no need to implement this as connection do get closed after the app goes down

Under normal circumstances, it would be fine. Though, there could be times where our NodeJS processes exit with the client-side DB connections being killed with the database server being unaware of the connections on the server-side need to be closed and hence potentially causing the DB server to have too many connections opened.

**Comment by cayter** [comment]
> > Drizzle ORM type doesn't define it, we'd have to define it ourselves but we can define the type and access it like this:
> > ```ts
> > import { type PostgresJsDatabase, drizzle } from "drizzle-orm/postgres-js";
> > 
> > export type DB<T extends Record<string, unknown>> =
> > 	PostgresJsDatabase<T> & {
> > 		session: {
> >                          // this won't show up on intellisense because drizzle orm has to support different drivers
> > 			client: postgres.Sql<T>;
> > 		};
> > 	};
> > 	
> > const orm = drizzle(client, { schema }) as DB<typeof schema>;
> > await orm.session.client.end(); // this is how postgres.js close the connections
> > ```
> 
> Great find! Since it is there, people can manage connections themselves according to their use cases. Is it in their docs?

Nope, I spent months playing around with their source code to realise this. :)

**Comment by mithleshjs** [comment]
I will add your solution to the docs in case someone is dealing with hanging connections or want to close connection manually. I am also accepting PR in case you want to send it 😉

**Comment by andersbc** [comment]
Hi guys! 

I am trying to get this to work:
I have a module, `drizzle.module.ts`, in which set up two postgres db connections. I want the module to clean up after it self, using the  ´OnModuleDestroy' hook, but I can't figure out how to get a handle on the db connection.

There is a general answer given here: https://stackoverflow.com/questions/63753467/how-to-close-database-connection-in-nestjs-service, which I am trying to mimick, but it doesn't relate to `nestjs-drizzle`

Disclaimer: I am new to nestjs, this might just be me not understanding how the DI system works.

```ts
// file: drizzle.module.ts
import { Module, type OnModuleDestroy } from '@nestjs/common';
import { DB_CONN_MIGRATE, DB_CONN_QUERY } from '../constants';
import * as schema from './schema';
import { ConfigService } from '@nestjs/config';
import { DrizzlePostgresModule } from '@knaadh/nestjs-drizzle-postgres';
import { type PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import type postgres from 'postgres';

export type DB<T extends Record<string, unknown>> = PostgresJsDatabase<T> & {
  session: {
    client: postgres.Sql<T>;
  };
};

// This module provides two connections to the database using Drizzle:
// one for migrations and one for queries. The migration connection uses
// a single connection as recommended by Drizzle.

@Module({
  providers: [],
  imports: [
    DrizzlePostgresModule.registerAsync({
      tag: DB_CONN_MIGRATE,
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => {
        return {
          postgres: {
            url: configService.get<string>('DATABASE_URL'),
            config: { max: 1 }, // max one connection as recommended in Drizzle docs
          },
          config: { schema: { ...schema } },
        };
      },
    }),
    DrizzlePostgresModule.registerAsync({
      tag: DB_CONN_QUERY,
      inject: [ConfigService],
      useFactory: async (configService: ConfigService) => {
        return {
          postgres: {
            url: configService.get<string>('DATABASE_URL'),
          },
          config: { schema: { ...schema } },
        };
      },
    }),
  ],
})
export class DrizzleModule implements OnModuleDestroy {
  // Clean up the database connection
  onModuleDestroy() {
    console.log('Destroyed DrizzleModule');
    // how to get a handle on the database connection?
  }
}
```

**Comment by mithleshjs** [comment]
@andersbc You need to inject these services in the Module using their tags, then you can close the connection in Module destroy.

**Comment by andersbc** [comment]
Thanks, @mithleshjs  👍
For reference, following your advice, I changed the last part of my code example to:

```
export class DrizzleModule implements OnModuleDestroy {
  constructor(
    @Inject('DB_CONN_MIGRATE')
    private dbMigrate: DB<typeof schema>,
    @Inject('DB_CONN_QUERY')
    private dbQuery: DB<typeof schema>,
  ) {}
  async onModuleDestroy() {
    // Clean up the database connection
    await this.dbMigrate.session.client.end();
    await this.dbQuery.session.client.end();
    console.log('Destroyed DrizzleModule');
  }
}
```
