### ISSUE TITLE
Sqlite3 support

### ISSUE THREAD

**Issue by Vector-Green** [knaadh/nestjs-drizzle#9]
Hi, is it possible to support bun:sqlite3 and just sqlite3
or maybe just with universal driver)
I need this feature to make an embedded app)

**Comment by mithleshjs** [comment]
I am currently experimenting with Bun these days. So expect the driver for it dropping by the end of this week.

**Comment by mithleshjs** [comment]
> Hi, is it possible to support bun:sqlite3 and just sqlite3 or maybe just with universal driver) I need this feature to make an embedded app)

You can make a NestJS service and use bunsqlite. I can help you with it.
